name: CI

on:
  push:
    branches: ['master']
  pull_request:
    branches: ['master']
  workflow_dispatch:

env:
  TEST_TAG: henrytill/sdl-bits:test

jobs:
  ubuntu:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        compiler: [gcc, clang]
    steps:
      - uses: actions/checkout@v4
        with:
          submodules: recursive
      - uses: hendrikmuhs/ccache-action@v1.2.10
        with:
          key: ${{ github.job }}-${{ matrix.os }}-${{ matrix.compiler }}
      - name: Install dependencies
        run: |
          sudo apt install -yyq --no-install-recommends \
            libdrm-dev libgbm-dev \
            libsdl2-dev libfreetype-dev \
            liblua5.1-0-dev
      - name: Build
        run: make
        env:
          CC: ccache ${{ matrix.compiler }}
      - name: Test
        run: make check

  docker:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
        with:
          submodules: recursive
      - name: Set up QEMU
        uses: docker/setup-qemu-action@v2
      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v2
      - name: Build
        uses: docker/build-push-action@v4
        with:
          context: .
          push: false
          load: true
          tags: ${{ env.TEST_TAG }}
          cache-from: type=gha
          cache-to: type=gha,mode=max
      - name: Test
        run: docker run --rm --tty --workdir /home/build/sdl-bits ${{env.TEST_TAG}} make check

  windows:
    runs-on: windows-latest
    strategy:
      matrix:
        include:
          - { sys: mingw64, env: x86_64 }
          - { sys: clang64, env: clang-x86_64 }
          - { sys: ucrt64, env: ucrt-x86_64 }
    defaults:
      run:
        shell: msys2 {0}
    steps:
      - uses: actions/checkout@v3
        with:
          submodules: recursive
      - uses: msys2/setup-msys2@v2
        with:
          msystem: ${{matrix.sys}}
          install: >-
            mingw-w64-${{matrix.env}}-toolchain
            mingw-w64-${{matrix.env}}-ninja
            mingw-w64-${{matrix.env}}-cmake
            mingw-w64-${{matrix.env}}-lua51
            mingw-w64-${{matrix.env}}-meson
            mingw-w64-${{matrix.env}}-SDL2
            mingw-w64-${{matrix.env}}-freetype
      - name: Check MSYSTEM
        run: echo $MSYSTEM
      - name: Build
        run: mingw32-make
      - name: Test
        run: mingw32-make check
